// Default Labels
export enum LabelText {
  ADD_CATEGORY = "添加分类",
  COLLAPSE_CATEGORY = "收起分类列表",
  NOTES = "笔记列表",
  CREATE_NEW_NOTE = "创建新笔记",
  DELETE_PERMANENTLY = "永久移除",
  DOWNLOAD = "下载",
  FAVORITES = "收藏",
  SCRATCHPAD = "草稿",
  MARK_AS_FAVORITE = "添加至收藏",
  MOVE_TO_TRASH = "移至回收站",
  NEW_NOTE = "新建笔记",
  REMOVE_CATEGORY = "从分类列表删除",
  REMOVE_FAVORITE = "移除收藏",
  MOVE_CATEGORY = "移动至",
  RESTORE_FROM_TRASH = "从回收站还原",
  SETTINGS = "设置",
  SYNC_NOTES = "同步",
  TRASH = "回收站",
  WELCOME_TO_TAKENOTE = "Welcome to Takenote!",
  RENAME = "重命名",
  ADD_CONTENT_NOTE = "Please add content to this new note to access the menu options.",
  DOWNLOAD_ALL_NOTES = "下载所有笔记",
  BACKUP_ALL_NOTES = "导出备份",
  IMPORT_BACKUP = "导入备份",
  TOGGLE_FAVORITE = "Toggle favorite",
  //github.dev is awesome
}
